global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

# https://prometheus.io/docs/prometheus/latest/configuration/configuration/#dns_sd_config

scrape_configs:
  - job_name: prometheus
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']
